[넘파이 사이트](https://numpy.org/)

In [1]:
#![제목](링크) - 이미지  (마크다운)

In [2]:
#[제목](링크) (마크다운)

# Numpy Tutorial

In [3]:
score = [12,34,56]

for i, s in enumerate(score):
    score[i] = s+3 
print (score)    


[15, 37, 59]


In [4]:
!pip install numpy

In [5]:
import numpy as np

np.__version__

'1.22.3'

## Numpy array

In [6]:
x = (10)
type(x)

int

In [7]:
y = (10,)
type(y)

tuple

In [8]:
#1D array shape 표현할 때 shape(4,)로 표현해야 함

In [9]:
xarr = np.array([1,2,3,4,5])
print(xarr)
xarr

[1 2 3 4 5]


array([1, 2, 3, 4, 5])

In [10]:
type(xarr)

numpy.ndarray

In [11]:
xarr.shape

(5,)

In [12]:
xarr.dtype

#int32, int64, float32, float64

dtype('int32')

In [13]:
xarr.size

#원소 개수

5

In [14]:
xarr.itemsize

#바이트 수

4

In [15]:
xarr.size * xarr.itemsize

#들어가는 메모리 확인

20

In [16]:
yarr = np.array([[10,11],[12,13],[15,16]])
yarr.shape

#두개짜리 원소 묶음이 3개있음

(3, 2)

In [17]:
zarr = np.array([[[1,2],[3,4]],[[5,6],[7,8]],[[9,10],[11,12]]])
zarr.shape

(3, 2, 2)

In [18]:
zarr

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [19]:
zarr.astype('float32')

#이걸로 데이터 타입이 바뀌진 않음

array([[[ 1.,  2.],
        [ 3.,  4.]],

       [[ 5.,  6.],
        [ 7.,  8.]],

       [[ 9., 10.],
        [11., 12.]]], dtype=float32)

In [20]:
zarr = zarr.astype('float32')
zarr.dtype

#선언해줘야 바뀜

dtype('float32')

In [21]:
xarr = np.array([1,2,3,4,5], dtype = 'float64')
xarr.dtype

#데이터 불러오면서 데이터 타입을 바꿀 수 있음

dtype('float64')

In [22]:
zarr = zarr.reshape(-1,3,2,2)
zarr.shape
#차원 주가시킬 때 -1은 적당히 함수에게 맡기는 느낌

(1, 3, 2, 2)

In [23]:
tarr = np.array([[[1,2],[3,4]],[[5,6],[7,8]],[[9,10],[11,12]]])
tarr = tarr.reshape(3,4)
tarr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [24]:
tarr = tarr.reshape(-1,2,2)
tarr

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [25]:
tarr.reshape(-1)

#tarr.flatten()과 같음

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [26]:
tarr[np.newaxis, :]

# 맨 앞에 차원 하나 추가하는 문법
# :의 위치에 따라 어디에 차원을 추가하는지가 달라짐

array([[[[ 1,  2],
         [ 3,  4]],

        [[ 5,  6],
         [ 7,  8]],

        [[ 9, 10],
         [11, 12]]]])

In [27]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
xarr = np.arange(0,20,2).reshape(5,2)
xarr

#파이썬의 range 이용해서 list 만드는 느낌

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10],
       [12, 14],
       [16, 18]])

In [29]:
np.linspace(1,2,10)

array([1.        , 1.11111111, 1.22222222, 1.33333333, 1.44444444,
       1.55555556, 1.66666667, 1.77777778, 1.88888889, 2.        ])

In [30]:
np.full((2,3),0)

array([[0, 0, 0],
       [0, 0, 0]])

In [31]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [32]:
np.zeros_like(zarr)

#zarr과 같은 배열의 데이터 만듬(원소는 0)

array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)

## Random

In [33]:
np.random.uniform(0, 10, 5)

#유니폼 분포

array([4.70560301, 0.55757705, 8.45382804, 8.45578596, 7.80360184])

In [34]:
np.random.normal(5,1,10)

#정규분포(평균값이 5이고 표준편차가 1인 정규분포)

array([5.32817708, 4.52503679, 5.50920476, 5.27906755, 4.97936619,
       5.3345257 , 5.96290802, 6.01662989, 4.59148082, 2.99585954])

In [35]:
np.random.randn(2,3)

#표준정규분포에 대해 데이터를 (2,3)만큼 만듦

array([[-1.79020059,  0.30390809,  0.64371068],
       [ 0.6250297 , -0.29686754,  0.82335197]])

## Function

In [36]:
xarr = np.arange(0,12).reshape(3,4)
xarr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [37]:
xarr.sum(axis=0)

#0번 축쪽으로 더함

array([12, 15, 18, 21])

In [38]:
np.sum(xarr, axis=1)

#1번 축쪽으로 더함

array([ 6, 22, 38])

In [39]:
xarr.mean(axis=0)
#np.mean(xarr, axis=0)과 같음

array([4., 5., 6., 7.])

In [40]:
xarr.min(axis=1)

array([0, 4, 8])

In [41]:
xarr + [3]
#Numpy는 BroadCasting이 가능 (단, 조건이 있음)

array([[ 3,  4,  5,  6],
       [ 7,  8,  9, 10],
       [11, 12, 13, 14]])

In [42]:
xarr * 2

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [43]:
x=np.array([[1,2],[3,4]])
y=np.array([[1,2],[3,4]])
x*y
#같은 위치의 원소끼리 곱

array([[ 1,  4],
       [ 9, 16]])

In [44]:
x@y
#우리가 아는 행렬 곱

array([[ 7, 10],
       [15, 22]])

In [45]:
x=np.array([1,2,3])
y=np.array([1,2,3])
np.dot(x,y)
#1차원일 때는 1*1+2*2+3*3으로 동작 (근데 1차원일 때도 걍 행렬 곱인데?)

14

In [46]:
x=np.array([[1,2],[3,4]])
y=np.array([[1,2],[3,4]])
np.dot(x,y)
#2차원 이상부터는 행렬 곱으로 동작

array([[ 7, 10],
       [15, 22]])

In [47]:
x=np.array([[1,2],[3,4]])
y=np.array([[1,2],[3,4]])
np.matmul(x,y)
#행렬 곱만 한다고 함

array([[ 7, 10],
       [15, 22]])

In [48]:
x=np.array([[1,2],[3,4],[5,6]])
y=np.array([[1,2,3],[3,4,5]])
np.dot(x,y)

array([[ 7, 10, 13],
       [15, 22, 29],
       [23, 34, 45]])

In [49]:
x=np.array([1,2,3])
x>2
#array로 결과가 나타나는데 거의 필터링을 위해서 씀

array([False, False,  True])

In [50]:
x[[False, False,  True]]
#Boolean indexing, True의 값만 뽑아옴 (x[x>2]와 똑같음)

array([3])

In [51]:
x[x<3]

array([1, 2])

In [52]:
x[x<3]=-2
x

array([-2, -2,  3])

In [53]:
x = [1,2,3]
y = [4,5,6]
np.concatenate((x,y), axis=0)

array([1, 2, 3, 4, 5, 6])

In [54]:
x = [1,2,3]
y = [4,5,6]
np.vstack((x,y))
#vertical로 합치기

array([[1, 2, 3],
       [4, 5, 6]])

In [55]:
x = [1,2,3]
y = [4,5,6]
np.hstack((x,y))
#horizon하게 합치기

array([1, 2, 3, 4, 5, 6])

In [56]:
x = [[1,2],[3,4]]
print(x[1][0])

3


In [57]:
x = np.array([[1,2],[3,4]])
x[1,0]
#x[row,culomn]

3

In [58]:
x = np.array([1,2,3,4,5])
np.where(x>3)
#()안이 true인 곳의 index를 뽑아줌

(array([3, 4], dtype=int64),)

In [59]:
np.where(x > 3, 1, 0)
#x>3인 곳은 1로, 아닌 곳은 0으로)

array([0, 0, 0, 1, 1])

In [60]:
x = np.array([1,2,3,4,5,6])
x = np.where(x>3,1,0)
x.sum()
#원하는 데이터의 개수를 구할 수 있음

3

In [61]:
x = np.random.randn(3,4)
x

array([[ 0.26462937,  1.02648051, -0.24263923, -1.19046868],
       [ 1.21471791,  0.65840104,  0.9229591 , -0.09875805],
       [-0.23244767, -0.96941863,  0.38984972,  0.52228466]])

In [62]:
np.argmax(x,axis=1)
# 제일 큰 값의 인덱스를 뽑아옴
#argmin은 그 반대

array([1, 0, 3], dtype=int64)

In [63]:
xarr = np.array([1,2,3,4,5,6,7])
xarr

array([1, 2, 3, 4, 5, 6, 7])

In [64]:
y = xarr[3:5].copy()
y
#.copy()를 해야 원본 데이터가 바뀌지 않음

array([4, 5])

In [65]:
y[0] = -1
y

array([-1,  5])

In [66]:
xarr

array([1, 2, 3, 4, 5, 6, 7])

In [68]:
iris = np.genfromtxt('datasets/iris.csv', delimiter = ',', skip_header=1)
iris[:5]

array([[1. , 5.1, 3.5, 1.4, 0.2, nan],
       [2. , 4.9, 3. , 1.4, 0.2, nan],
       [3. , 4.7, 3.2, 1.3, 0.2, nan],
       [4. , 4.6, 3.1, 1.5, 0.2, nan],
       [5. , 5. , 3.6, 1.4, 0.2, nan]])

In [69]:
#xarr[:,0] >5.8

m=5.8
x = iris[iris[:,0] >5.8, :]
y = iris[iris[:,0] >5.8, :]

In [70]:
np.savez('my_iris.npz', x=x, y=y)

In [71]:
my_iris = np.load('my_iris.npz')

In [72]:
type(my_iris)

numpy.lib.npyio.NpzFile

In [73]:
xarr = my_iris['x']
yarr = my_iris['y']
#저장 후 로드해서 다시 데이터 볼 수 있음

In [75]:
xarr[:10]

array([[ 6. ,  5.4,  3.9,  1.7,  0.4,  nan],
       [ 7. ,  4.6,  3.4,  1.4,  0.3,  nan],
       [ 8. ,  5. ,  3.4,  1.5,  0.2,  nan],
       [ 9. ,  4.4,  2.9,  1.4,  0.2,  nan],
       [10. ,  4.9,  3.1,  1.5,  0.1,  nan],
       [11. ,  5.4,  3.7,  1.5,  0.2,  nan],
       [12. ,  4.8,  3.4,  1.6,  0.2,  nan],
       [13. ,  4.8,  3. ,  1.4,  0.1,  nan],
       [14. ,  4.3,  3. ,  1.1,  0.1,  nan],
       [15. ,  5.8,  4. ,  1.2,  0.2,  nan]])

In [76]:
yarr[:10]

array([[ 6. ,  5.4,  3.9,  1.7,  0.4,  nan],
       [ 7. ,  4.6,  3.4,  1.4,  0.3,  nan],
       [ 8. ,  5. ,  3.4,  1.5,  0.2,  nan],
       [ 9. ,  4.4,  2.9,  1.4,  0.2,  nan],
       [10. ,  4.9,  3.1,  1.5,  0.1,  nan],
       [11. ,  5.4,  3.7,  1.5,  0.2,  nan],
       [12. ,  4.8,  3.4,  1.6,  0.2,  nan],
       [13. ,  4.8,  3. ,  1.4,  0.1,  nan],
       [14. ,  4.3,  3. ,  1.1,  0.1,  nan],
       [15. ,  5.8,  4. ,  1.2,  0.2,  nan]])